#define F (1<<14)
#define INT_MAX ((1<<31)-1)
#define INT_MIN (-(1<<31))
#define INT_TO_FP(n)((n)*(F))
#define CONVERT_TO_INT_NEAR(x) (((x)>=0 ? ((x)+(F)/2)/(F) : ((x)-(F)/2)/(F)))
#define FP_TO_INT(x) ((x)/(F))
#define ADD_FP(x,y) ((x)+(y))
#define ADD_MIXED(x,n) ((x)+(n)*(F))
#define SUB_FP(x,y)((x)-(y))
#define SUB_MIXED(x,n) ((x)-(n)*(F))
#define MULT_FP(x,y) (((int64_t)(x))*(y)/(F))
#define MULT_MIXED(x,n) ((x)*(n))
#define DIV_FP(x,y) (((int64_t)(x))*(F)/(y))
#define DIV_MIXED(x,n) ((x)/(n))

